name: tarjeta_lealtad
description: Tarjeta de lealtad digital (instancia por negocio)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#120404"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
